export const FETCH_CURRENT_USER_STARTED = 'FETCH_CURRENT_USER_STARTED';
export const FETCH_CURRENT_USER_SUCCEEDED = 'FETCH_CURRENT_USER_SUCCEEDED';
export const FETCH_CURRENT_USER_FAILED = 'FETCH_CURRENT_USER_FAILED';
export const SET_USER = 'SET_USER';
