export const FETCH_PROJECTS_STARTED = 'FETCH_PROJECTS_STARTED';
export const FETCH_PROJECTS_SUCCEEDED = 'FETCH_PROJECTS_SUCCEEDED';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';

export const FETCH_SINGLE_PROJECT_STARTED = 'FETCH_SINGLE_PROJECT_STARTED';
export const FETCH_SINGLE_PROJECT_SUCCEEDED = 'FETCH_SINGLE_PROJECT_SUCCEEDED';
export const FETCH_SINGLE_PROJECT_FAILED = 'FETCH_SINGLE_PROJECT_FAILED';
